### ISSUE TITLE
Make onboarding video

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#112]
Need to make an onboarding video that goes over the most important stuff:

- The reasons that one can be removed from CodeDoesGood
- Google Drive procedures
- Kanban procedures

Need to make slides for this

**Comment by abbeyjackson** [comment]
Irma and/or Alidia

**Comment by abbeyjackson** [comment]
@irmattg Hey how is this coming along?

**Comment by abbeyjackson** [comment]
@irmattg is updating the slides to be more point form

I am working with @swiftcode to get the rest of the wiki pages complete and then we can finish these videos

**Comment by abbeyjackson** [comment]
@irmattg is done her part of this, I need to record the audio now so assigning to me.

**Comment by abbeyjackson** [comment]
Audio is done and is being fixed by @iamthepanda

**Comment by abbeyjackson** [comment]
I re-recorded the audio and gave the better version to @irmattg so @iamthepanda will no longer be fixing anything :)

**Comment by irmattg** [comment]
@abbeyjackson just finished up. the video total time is 16 mins, i cut out some parts. any "ums" or silences to make it a tad shorter. it's uploading now to my google drive and will post link here :) feel free to let me know if any changes or edits. 

i was thinking of adding a screen recording of some of the pages in the wiki, but was thinking that it wouldn't fit since the volunteer watching will probably not having time to read it all. but thought it'd be good to use a visual for the wiki to get the volunteer familiar with reading the wiki pages.

**Comment by irmattg** [comment]
@abbeyjackson Completed here https://drive.google.com/file/d/0Bz3jsfRsa8bsaGxSNXNKUmxhbVk/view?usp=sharing

**Comment by abbeyjackson** [comment]
That's a great idea, why don't you go ahead and run with that? :)

**Comment by iamthepanda** [comment]
@abbeyjackson @irmattg I have modified irma's video to further remove unnecessary bits("ums", "you knows", silences, repeated words, stutters). I have also added some pauses in certain areas for effect as well as for pacing. Total video time is now 15 minutes.
Video has been posted as an unlisted video on youtube and may be viewed [here](https://youtu.be/CtTdJRi0V5s)
I can upload it elsewhere as an mp4 if desired.

**Comment by abbeyjackson** [comment]
@iamthepanda thanks for taking the initiative! Irma is still working on the video though so we can not use the edits you did (see the last comments where she suggests she will add more slides)

**Comment by iamthepanda** [comment]
@abbeyjackson no problem. @irmattg just let me know if you'd like to collab.

**Comment by irmattg** [comment]
@iamthepanda George that's awesome that you took time to further modify the video! Once I add in the extra slides, I can send it over to you if you'd like to make any changes.

**Comment by irmattg** [comment]
@abbeyjackson uploading right now to my gdrive

**Comment by abbeyjackson** [comment]
Great job Irma!
