### ISSUE TITLE
Update Kanban wiki page

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#113]
There are now multiple kanban boards, need to update the wiki page to reflect that also add screenshots etc about how to manage issues

**Comment by abbeyjackson** [comment]
hold off until the video is done

**Comment by abbeyjackson** [comment]
I went over it and it's fine, added links to the boards.

@GrfxGuru for this task instead of changing it mostly I just need you to make it more succinct, add more whitespace. It's a wall of text which makes it difficult to absorb. When I have the video recorded I will add a link also.

**Comment by GrfxGuru** [comment]
I will reformat per request.

**Comment by GrfxGuru** [comment]
Updated some of the content and formatting, will close ticket, content is still lengthy but needed. The video will solve the problem I believe.
