### ISSUE TITLE
write managing your work wiki page

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#121]

**Comment by swiftcode** [comment]
@abbeyjackson The first draft is done and awaiting some feedback.

**Comment by abbeyjackson** [comment]
I should have some time tomorrow :)
-- 

Sincerely,

Abbey Jackson

604-600-1450 <javascript:void(0);>
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey

**Comment by swiftcode** [comment]
Working on revisions of this per Abbey's suggestions.

**Comment by swiftcode** [comment]
Working on a mock-up of an actual example.  Progress has been made, but not integrated into existing wiki.  Will upload additional changes once mock-up is completed.
