### ISSUE TITLE
Add QA info

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#125]
Add information about why we do not have a QA department

**Comment by swiftcode** [comment]
@abbeyjackson Not completed yet.  Still on the to-do list.

**Comment by swiftcode** [comment]
WIP 06/04

**Comment by swiftcode** [comment]
No progress. Will write up a paragraph week of 06-12.

**Comment by swiftcode** [comment]
Closing out old ticket.  Not a relevant issue, any longer.
