### ISSUE TITLE
Go through designers

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#128]
Add a column to volunteer reports, we need to know if a designer is a graphic designer or has experience with app design / wants to do app design if they have no experience

**Comment by abbeyjackson** [comment]
I think this is done, but it was sitting open. Peter can you please check and if it is please close the ticket. Thanks!

**Comment by GrfxGuru** [comment]
I will check.

**Comment by GrfxGuru** [comment]
I have added the extra column and changed designer to app and web designer. I have also updated volunteer data into those columns.
