### ISSUE TITLE
Hook GH to Volunteer Software

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#129]
Is it possible to be able to pull up a report of people that have open tickets which have not been updated that week?

**Comment by brandonpas** [comment]
We could leverage the GitHub API to pull this information. Perhaps using the following API and reviewing each of the "issue" objects for the "updated_at" value:  https://developer.github.com/v3/issues/events/#list-events-for-a-repository

**Comment by swiftcode** [comment]
The integration is pending a slack account.

**Comment by abbeyjackson** [comment]
part of VSW (Mercury) and captured in the specification document
