### ISSUE TITLE
Figure out costs for InVision or Marvel app service

### ISSUE THREAD

**Issue by 98chimp** [CodeDoesGood/business#133]

**Comment by 98chimp** [comment]
No special pricing for non-profits advertised on their respective company sites.
General pricing & plans are:
Marvel: [https://marvelapp.com/plans/](url)
InVision: [https://www.invisionapp.com/plans](url)

Have sent individual emails to both companies to inquire further.

**Comment by 98chimp** [comment]
Just got a reply from InVision

In essence, they have a 20% discount towards any plan refunded after full payment is made and proof of NPO status provided as per instructions found in the enclosed screenshot.

<img width="1459" alt="screenshot 2017-05-01 22 37 07" src="https://cloud.githubusercontent.com/assets/10504371/25605301/c6204620-2ebe-11e7-83cc-a6d9a09e931d.png">

**Comment by 98chimp** [comment]
Another reply came in from Marvel

They are willing to provide a 50% discount on any of their annual plans (see screenshot below).

<img width="867" alt="screenshot 2017-05-02 06 12 45" src="https://cloud.githubusercontent.com/assets/10504371/25619117/88acd3ae-2efe-11e7-819d-ef331744ba6e.png">

**Comment by 98chimp** [comment]
@abbeyjackson we will need funds before we can commit to any of these plans
even at 50% discount, these could mean upwards of $40US/month for a team of 4-5 designers

**Comment by abbeyjackson** [comment]
@98chimp fantastic! Good job going the extra mile :)

Until we have our status (and income) is it feasible to have our designers just use a personal free account for the project that they design?

**Comment by abbeyjackson** [comment]
@98chimp see above question

**Comment by 98chimp** [comment]
i'm okay with that for sure!
if they're okay with it
@abbeyjackson

**Comment by abbeyjackson** [comment]
I'm closing this issue as I feel we have enough information to go forward
