### ISSUE TITLE
Development related Slack integrations

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#134]
Look into the following Slack integrations:
- Github for PR notifications posted to project channel
- Travis CI for notifications of failed builds posted to project channel
- Crashlytics for notifications of major issues posted to a dedicated channel (this one is lowest priority)

Travis integration is being carried out by @festrs @gopesh @abhishek_sinha (slack usernames), please coordinate with them for anything needed

**Comment by swiftcode** [comment]
I setup the integration with dev-ios and dev-android. What is the process going to be to test this?

I did get the message that we are running out of slots when I did the android setup.

**Comment by abbeyjackson** [comment]
@swiftcode you can push an empty commit to the ios-template and android-template repos to test

**Comment by abbeyjackson** [comment]
@swiftcode also if you do run out of integrations make a list of what you think should still be added. When we have our non profit status finalized we will have more integrations available because Slack has a different account scheme for non-profits.

**Comment by swiftcode** [comment]
@abbeyjackson Yes, I can push empty commits.  I'll try to get it done sometime today, if not, then this evening.  

I'll make a list, should be run out.

**Comment by swiftcode** [comment]
This integration can only be implemented by someone with Admin privileges.  I made the issue known to @abbeyjackson @northtwilight.  We need to have an account that would be responsible for the integration.  This is being worked on.

**Comment by swiftcode** [comment]
I sent a ticket into GitHub support with out issue.  GitHub responded that this is a Slack issue.  I created a ticket with Slack support and they indicated they are assigning someone to look into it for us.

@northtwilight @abbeyjackson

**Comment by abbeyjackson** [comment]
Thanks @swiftcode for keeping me in the loop!

**Comment by swiftcode** [comment]
@northtwilight @abbeyjackson Who is the main contact for this?  When there's time, I want to discuss the two options for integration and decide which will work best for the org.

**Comment by abbeyjackson** [comment]
@swiftcode Sorry I missed this tag, as per slack discussion we will use a slack account, contact Peter Witham to get an account made using the volunteers email address.

**Comment by GrfxGuru** [comment]
I will take care of creating the account and get in touch with you @swiftcode. It was already on my radar but wanted to get this comment on the task.

**Comment by swiftcode** [comment]
This is waiting for a slack account.  Will finish, when the account is ready.

**Comment by swiftcode** [comment]
I created the integration using the voluteers account from both Slack and GitHub.  

TODO:  I will either add an empty commit to test or see if we have any code that's ready for a PR.  I will reach out to the Android side and see if they have anything, as well.

**Comment by swiftcode** [comment]
Closing out an old ticket.  Was completed a long time ago, in a galaxy far, far away.
