### ISSUE TITLE
Upload photos

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#136]
Using the method Alidia suggested, upload photos

**Comment by abbeyjackson** [comment]
@renatomcamilio We are still having issues getting the photos off of the phone, will let you know when we've got them :)

**Comment by alidiafindley** [comment]
@abbeyjackson Anything I can do to assist on this?

**Comment by abbeyjackson** [comment]
No, there doesn't seem to be a way to get only one folder off of an iPhone.
I am not sure what we will do. He has 4000 photos in this folder we want to
be able to go through but around 15000 total on his phone so we can't
easily pick out the ones we want.
-- 

Sincerely,

Abbey Jackson

604-600-1450 <javascript:void(0);>
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey
