### ISSUE TITLE
Edit communication wiki page

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#140]
link to contact page

**Comment by abbeyjackson** [comment]
sentence about the video in the onboarding email

**Comment by alidiafindley** [comment]
@abbeyjackson just to confirm - did you want the "contact us" link included in the procedural, technical, or external communications section? And should the sentence about the video in the onboarding email go under procedural?

**Comment by abbeyjackson** [comment]
@alidiafindley Let's just add a note to the very bottom that says if you need to contact a team or person directly please visit our contact page for details

I think the sentence about the video that will be in their onboarding email actually shouldn't be on this page. It should be on the onboarding page in the section about slack.

On the communication page please delete the info about growbot as I've removed it from our slack.

**Comment by alidiafindley** [comment]
@abbeyjackson Added sentence on contact [here](https://github.com/CodeDoesGood/business/wiki/2.-Communication#contact), and removed section on Growbot.

Added sentence on onboarding email video [here](https://github.com/CodeDoesGood/business/wiki/2.-Onboarding#slack).

**Comment by alidiafindley** [comment]
@abbeyjackson Just wanted to check status on this one -- are the changes I made sufficient? If so, is this issue ready to close?

**Comment by abbeyjackson** [comment]
@alidiafindley if all the fixes are done go ahead and close it, you don't need to ask :) Did you update the incorrect slack channel names?

**Comment by alidiafindley** [comment]
@abbeyjackson I updated those I could find! I can't find #networking or #updates in Slack, have those been phased out or renamed something very different?

**Comment by abbeyjackson** [comment]
I think those are both gone
