### ISSUE TITLE
Git commit template

### ISSUE THREAD

**Issue by swiftcode** [CodeDoesGood/business#143]
Set up a commit template that will work with SourceTree for iOS and if there is a common GUI for Android, should work with that as well.

Template to comply with:  https://github.com/CodeDoesGood/org/wiki/3.-Git-Procedures

**Comment by swiftcode** [comment]
@abbeyjackson Can this be closed?  If something needs to be revised, we could re-open or open a new ticket.

**Comment by abbeyjackson** [comment]
If it's done to your satisfaction give it a close. I am trusting the volunteers on these tasks as I don't have time to check everything right now :)

**Comment by swiftcode** [comment]
This is a good first step.  If there are opinions on the matter, we can always update the wiki.
