### ISSUE TITLE
Add integration document to wiki

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#144]
This page should include information about slack integrations as well as Travis CI and whatever other integrations have been added.

Please coordinate with people assigned to the following tickets:
Development related Slack integrations https://github.com/CodeDoesGood/org/issues/134
Integrate CI with Github https://github.com/CodeDoesGood/org/issues/89
Look at integrating Danger with Github https://github.com/CodeDoesGood/org/issues/109 (not yet in progress)

If someone wants to do issue #109 that would be great also

**Comment by abbeyjackson** [comment]
@swiftcode how is this coming?

**Comment by swiftcode** [comment]
OK.  So, I received some information black from Slack on the process.  I'm currently writing up a summary to present  on our options and which option seems best given our setup.  There's two paths - authed and unauthed.  I thought it best to put the documentation in place once we decide which setup we'll use and get  a working test in place.  

I've found that the documentation that's already existing is pretty good.  We can grab the processes out of that documentation that meets out current need and just add that to our Wiki,

**Comment by abbeyjackson** [comment]
Really fantastic work, thanks Michael! As you have ownership of this task
please let me know what the difference is between the two but give me your
recommendation. Unless there is something specific about CDG you are
unaware of we will likely go with your recommendation.

**Comment by swiftcode** [comment]
This will follow getting the actual integration completed (which is WIP).

**Comment by swiftcode** [comment]
The documentation is on the Wiki page.
