### ISSUE TITLE
Add info about private channels to wiki

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#148]
There is no info in the wiki about what to do with adding someone to a private channel. We need to add that information:

Team leads are free to add volunteers to their team channel. They must however make sure @peterwitham knows so that he can mark that on the volunteer spreadsheet so we know the volunteer is assigned a role.

**Comment by alidiafindley** [comment]
Added [here](https://github.com/CodeDoesGood/business/wiki/2.-Communication#private-channels).

**Comment by abbeyjackson** [comment]
Awesome thanks!
