### ISSUE TITLE
Data base architecture design for volunteer software back end

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#150]
Under mentorship of Renato

**Comment by DirkDeVisser** [comment]
We are using [umlet](http://umlet.com/) for the design. The file can be found on Google Drive.
I have made a basic start,  Renato will give feedback on it this weekend.

**Comment by abbeyjackson** [comment]
@renatomcamilio @DirkDeVisser where are we at with this? The database needs to be architected before development can start. The project is ready to go ahead but we need the database done first so our developers have an API to hook into.

**Comment by renatomcamilio** [comment]
So, the database architecture is a design, not a concrete API to be hooked into. I haven't been following the conversation on how to implement, but this effort with Dirk and Brandon was a design concept, not the implementation itself.

The way I see is: the models will be defined in code, using a ORM (not sure which backend stack is set for this project, but say Knex.js/Bookshelf.js in case it's Node.js)

I have to catch up with Brandon and Dirk, and will post an update here.

**Comment by abbeyjackson** [comment]
Yeah sorry those were two separate thoughts :)

The database needs to be architected...and then the backend devs need to build an API with it as we need an API for the front end and mobile apps to hook into

**Comment by DirkDeVisser** [comment]
Database design is done, other discussion about this should take place in [Mercury-Web](https://github.com/CodeDoesGood/Mercury-Web)
