### ISSUE TITLE
Add all volunteers to announcement google group

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#152]
We use groups for google drive access. There is also an announcement google group that has no drive access but which we can use to send out emails. We will not use this often as we will be using Slack and our volunteer software but as we don't have that set up yet I'd like everyone added to this so I can contact them.

In the future please add all users to this group as the final step in their onboarding (after they are confirmed to have their profile set up meaning they have looked at their onboarding link)

**Comment by GrfxGuru** [comment]
I have added the other groups to the Announcements group. That should take care of this, new members to other groups should be automatically included if I am reading it right.

**Comment by abbeyjackson** [comment]
@GrfxGuru no this won't work because not everyone at CDG has Google Drive access yet. 

You'll have to add each address individually rather than use groups. This is a temporary list that will not be used once Mercury is made btw so we don't need to worry about managing people on and off the list over time but using groups in addition to individual emails would mean that some people may end up getting the email more than once if their email is added and then in a couple week's they're given drive access.

**Comment by GrfxGuru** [comment]
Oh OK, I'll take care of it.

**Comment by GrfxGuru** [comment]
Current users have been added manually.
