### ISSUE TITLE
Add all mentors to mentor room on Slack

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#154]
Massimo and Renato went through our applications for people that wanted to be mentors. Most people stayed labelled as mentors but some were changed to Hatchling 7 which just means we want to see them on a project before we put them in charge.

Please check with Massimo to make sure that the reports are up to date and then add all mentors of all platforms to the #general-mentors channel. Team leads should not be invited except Chris Myers since he is dev hatchery team lead.

**Comment by GrfxGuru** [comment]
Invites have been sent to mentors to join the channel.
