### ISSUE TITLE
Go through Project boards

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#155]
There are some issues that have been added via the Issues tab and then not added to a project board. Need to find these and put them on their appropriate board.

**Comment by vitalii-tym** [comment]
@abbeyjackson I'd like to do this, but not sure I see all the boards. There are "Business Tasks" and "Meetings" and they are in read-only mode. Should I contact Peter or Chris via Slack?

**Comment by abbeyjackson** [comment]
@vitalii-tym Can you see these boards? https://github.com/orgs/CodeDoesGood/projects

**Comment by vitalii-tym** [comment]
@abbeyjackson No. Its 404.

**Comment by abbeyjackson** [comment]
@vitalii-tym contact either Peter Witham or Chris Myers and they'll be able to give you github access. Then I can talk with you about this task tomorrow. We have a meeting tonight so I won't have time today.

**Comment by GrfxGuru** [comment]
Noticed this comment from @abbeyjackson and have sent you a GitHub invite @vitalii-tym

**Comment by vitalii-tym** [comment]
@GrfxGuru, thanks. Everything works now. Will run through boards in my nearest available time.
@abbeyjackson this task is clear enough to go with. If there are any special things I should take into account - let me know. 
By default I'll make sure there no issues without boards. All "free" issues will be put into respective boards in the proper columns.

**Comment by abbeyjackson** [comment]
Fantastic! The only thing to be aware of is every issue should have a
label, but only one label. Thanks!

**Comment by vitalii-tym** [comment]
Almost done. There are only a few issues with no labels left.
@abbeyjackson Abbey, I've got a question: since all issues should have a label I found no label for issues, which are an actual work. I mean not a just a "bug" or "enhancement", but real hard work, required to move the respective project forward. Should we create one?

**Comment by abbeyjackson** [comment]
@vitalii-tym  Can you give me a link to one please so I don't give you the wrong information?

**Comment by vitalii-tym** [comment]
@abbeyjackson This one for example: https://github.com/CodeDoesGood/org-website/issues/14
Doesn't look like just an enhancement, but rather a piece of required work to have v2 of org website built.

**Comment by abbeyjackson** [comment]
@vitalii-tym  Ahh okay so the lead mentor should manage the project boards for the project repos. They do not have to use labels if they don't want to. 

This ticket was only for our business project board:
https://github.com/CodeDoesGood/business/projects/2
and our organizational level project boards:
https://github.com/orgs/CodeDoesGood/projects

Sorry about that, I didn't even think about the boards that were on our actual repositories. That's great that you went through those also though! I haven't looked at any of them to be honest.

**Comment by vitalii-tym** [comment]
@abbeyjackson Its OK. It was a great opportunity for me to get a better idea about the current state of the projects.
All tasks are on boards, have labels (with a few exceptions I mentioned before), in proper columns, and "In Progress" tasks have assignees.
Closing this issue now.
