### ISSUE TITLE
List of Business & Law schools

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#169]
It will be helpful to have a list of business and law schools in Canada for future recruiting of volunteers.

Compile a list of contact information for business and law schools in major Canadian cities. The list does not have to be exhaustive but should cover the biggest schools at least.  The contact information we need are for whomever we would speak to about recruiting students for volunteer jobs.

**Comment by mattwalo32** [comment]
[Schools.pdf](https://github.com/CodeDoesGood/business/files/1040217/Schools.pdf)

**Comment by alidiafindley** [comment]
Uploaded on the Drive [here](https://drive.google.com/a/codedoesgood.org/file/d/0BzVr9LT9ayq9ajZ1OHpUdEo3TDQ/view?usp=sharing).

**Comment by abbeyjackson** [comment]
Awesome, thanks! You can close the issue 👍
-- 

Sincerely,

Abbey Jackson

604-600-1450 <javascript:void(0);>
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey

**Comment by alidiafindley** [comment]
Updated link [here](https://docs.google.com/a/codedoesgood.org/document/d/1MI6KAAZIWQ7Lmz6EIf31wJV8jhB21bpehsjY3drtER4/edit?usp=sharing).
