### ISSUE TITLE
List of Meetups

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#175]
Compile a list of the largest tech, volunteer, and social good type meet ups in Canada. Again does not need to be exhaustive, just find me the 5 biggest in each category.

**Comment by irmattg** [comment]
Hi Abbey, still working on this.

**Comment by irmattg** [comment]
@abbeyjackson 
Canada Meetups
--
Tech 
http://ladieslearningcode.com/
https://www.meetup.com/DevHouse-Waterloo/
https://www.meetup.com/Toronto-User-Experience-Designers/
https://www.meetup.com/VanDev/
https://www.redacademy.com/community-projects/
Volunteer 
http://peacegeeks.org/volunteer
http://jacanada.org/volunteers
http://www.saveourscruff.org/
http://freegeekvancouver.org/
Social good 
https://www.meetup.com/HackerNestKW/
https://www.meetup.com/Hacking-Health-Waterloo/
https://www.techsoupcanada.ca/en/community/blog/hold-a-nonprofit-tech-meetup-in-your-city
http://info.techsoup.org/airbnb/

**Comment by abbeyjackson** [comment]
Irma can you tag Alidia (I'm on my phone and don't know her GitHub
username) to find out where the google doc for this list is and then add
these there? Thanks! And great work!!
-- 

Sincerely,

Abbey Jackson

604-600-1450 <javascript:void(0);>
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey

**Comment by alidiafindley** [comment]
@abbeyjackson Sorry never got a notification for this -- just saw it in my audit! Went ahead and added the links to the doc right away.

On the Drive [here](https://docs.google.com/a/codedoesgood.org/document/d/1nXYpLzUcIOND38DDk7Z9glo7ZNVHIdlgpBx0GRrg58U/edit?usp=sharing).
