### ISSUE TITLE
About us video

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#177]
Create a video that only has slides for our mission and guiding principles.

One per slide so that we can pause and talk about each one individually. 

Slide One: It should have the same animated title screen
Slide Two: an intro that says "Our Mission and Guiding Principles"
Slide Three: MISSION in smaller letters to the top left and the mission written in bigger letters in the middle. 
Slide Four: GUIDING PRINCIPLES on it's own screen
Slide 5-14: All the principles one by one the same way the mission was done (with GUIDING PRINCIPLES up to the left in smaller writing).
Slide 15: BELIEFS AND VALUES same way as Slide Four

**Comment by abbeyjackson** [comment]
Irma will do the slides, I am doing the audio

**Comment by abbeyjackson** [comment]
@irmattg please add a last page that says Beliefs and Values in large text and "We believe every human on this planet should be treated with dignity and respect and should be extended the same basic rights as each other" in smaller letters.

**Comment by abbeyjackson** [comment]
I updated the ticket description above. The information about who we are up until I start talking about our mission should be on the first slide or insert a new slide you think is relevant between the intro screen and Slide Two

**Comment by irmattg** [comment]
@abbeyjackson Thanks for the info Abbey. 

1. I'll work on adding the audio to the video. 
2. I'll also add a last page that says Beliefs and Values with the message you mentioned above.

**Comment by irmattg** [comment]
@abbeyjackson 

Completed :) Please let me know if any changes are necessary. 
https://drive.google.com/file/d/0Bz3jsfRsa8bsSnVzLXVtVVlFV0k/view?usp=sharing

**Comment by abbeyjackson** [comment]
@irmattg fantastic! Thank you! Only one change needed. When you load the video, before you press play, slide 2 is displayed. The slide that should be displayed is the first one with our name on it.

**Comment by abbeyjackson** [comment]
@irmattg I'm just thinking now...the first slide "Who are we" is on screen for a really long time. Maybe we can add a few more in there that make sense? For example you could have "Low cost software for non-profits" as one. The issue I am seeing is that it's hard to keep attention for the length of time of that single screen, even I couldn't do it and it's my video. If you're not sure what other slides to add you can post in #general on slack and ask if someone can watch it and help you figure it out.

**Comment by irmattg** [comment]
@abbeyjackson will return to the comment above once I finish up https://github.com/CodeDoesGood/business/issues/112

**Comment by irmattg** [comment]
@abbeyjackson uploading now to my Gdrive for review.

**Comment by irmattg** [comment]
@abbeyjackson 

Completed - https://drive.google.com/file/d/0Bz3jsfRsa8bsUmo1X1pSNU1UU00/view?usp=sharing

**Comment by abbeyjackson** [comment]
@irmattg When I first open the link the screen is on point #2 (see below). Can you please make the default screen when the video is accessed the first screen? (the one with the company's name)

<img width="1234" alt="screen shot 2017-07-09 at 5 31 21 pm" src="https://user-images.githubusercontent.com/11657280/27999014-906f793a-64cc-11e7-812b-55e889604d0f.png">

**Comment by abbeyjackson** [comment]
Otherwise it's great!

**Comment by abbeyjackson** [comment]
I love the images you added :)

**Comment by irmattg** [comment]
Awesome! @abbeyjackson I'll try and see if that's possible. I think that may just be a random slide that is picked when I uploaded to Gdrive. Will we be uploading these to a youtube channel? Or they'll go on the CDG drive?

**Comment by abbeyjackson** [comment]
@irmattg this is fantastic, thank you! I'm closing the issue.
