### ISSUE TITLE
Move articles from business wiki to dev hatchery

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#186]
The following articles should be moved to the dev hatchery wiki.

1. Copy the article over.
2. Add a star (*) to the beginning of the title so that it shows up at the top of the dev hatchery
3. Delete from the business wiki
4. Delete from the home page of the business wiki
5. Check Onboarding wiki page to make sure none of the moved articles are linked to the old address.

Making Estimates
Managing Your Work
Pull Requests & Code Review
Writing Tickets & User Stories

**Comment by swiftcode** [comment]
On list for week of 06-21

**Comment by swiftcode** [comment]
Putting on hold.  Not relevant as the volunteer structure has changed.  Can reopen at a later point.
