### ISSUE TITLE
Article on Mentoring

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#187]
This is a super subjective subject but at least something to start off our new mentors who aren't sure what to do. At the very least please  emphasize the power of screensharing (Screenhero) and using slack to have audio calls to explain things as it is often quicker and more effective than chatting. Also recommend finding really good articles written on the topic as I'm sure there are many and include a "more links" session at the bottom.

**Comment by swiftcode** [comment]
Haven't gotten to this yet.  On my todo list

**Comment by swiftcode** [comment]
Not relevant any longer.  Closing.
