### ISSUE TITLE
Look up new grant info

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#191]
There was new grant info announced in this year's Canadian budget. It is for groups that are teaching tech. Please look into this and get the details of what we need to do to apply and qualify as well as what the grant actually is for.

**Comment by alidiafindley** [comment]
@abbeyjackson Working on this now! Just on a first look there's a ton of grants and funds in the budget aimed towards groups that teach tech skills -- do you want information on all of them, or is there one in particular you had heard of? Either way I'll make sure we have info on all relevant ones for #168 .

Doc created [here](https://docs.google.com/a/codedoesgood.org/document/d/1CZkZN2wU1x_4pJ-QLINjC-CjylxBKhUxBQ1mQoufmxM/edit?usp=sharing).

**Comment by abbeyjackson** [comment]
I don't know about any specifically, just I read the announcement that new
money was being allocated in this domain. So lets say I want a list of all
of them :)

Also we should look for other grants like the ones that Facebook, Google
and other organizations give out.
-- 

Sincerely,

Abbey Jackson

604-600-1450 <javascript:void(0);>
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey

**Comment by alidiafindley** [comment]
@abbeyjackson You got it! If it's alright with you then, I'll include all of the grant info in one document and merge this issue into the existing list of grants under #168 .

**Comment by abbeyjackson** [comment]
Yeah perfect, you might as well close this issue.

Btw good job getting the hang of the boards so quickly!
-- 

Sincerely,

Abbey Jackson

604-600-1450 <javascript:void(0);>
https://github.com/abbeyjackson
http://ca.linkedin.com/in/earthabbey

**Comment by alidiafindley** [comment]
Closing this since the info will be included in general grants list! See #168 . ☺️
