### ISSUE TITLE
Add Design lecture link to DevHatchery tasks' list once that is set up

### ISSUE THREAD

**Issue by northtwilight** [CodeDoesGood/business#192]
The latest Worldwide Developers' Conference at Apple has a link to an hour-long video on 'Essential Design Principles' that does an excellent job of covering these. 

I just realised the link requires a developer account at Apple therefore it can't be required viewing for CDG hatchlings, but for those devs with an account, it's great for a review or gentle introduction.

The video is available here.
https://developer.apple.com/videos/play/wwdc2017/802/

**Comment by abbeyjackson** [comment]
Massimo how about you add a Design Principles page to the Dev Hatchery and
include it as a link. Apple dev accounts are actually free now, you only
pay if you want to be able to put an app in the app store. We can't force
people to register but it would be good to let them know it's there for
their info. There was a really good video last year on designing accessible
apps, I'd like that link added also if you do this :)

**Comment by abbeyjackson** [comment]
@northtwilight 

Massimo how about you add a Design Principles page to the Dev Hatchery and
include it as a link. Apple dev accounts are actually free now, you only
pay if you want to be able to put an app in the app store. We can't force
people to register but it would be good to let them know it's there for
their info. There was a really good video last year on designing accessible
apps, I'd like that link added also if you do this :)

Also I'm not clear what you mean by the "Dev Hatchery tasks list once that is set up" What dev hatchery task list?

**Comment by northtwilight** [comment]
I meant the Dev Hatchery project...
https://github.com/orgs/CodeDoesGood/projects/9
- will fill this in tomorrow!

**Comment by abbeyjackson** [comment]
Okay I'm still not completely clear. Is this issue to remind you to add something to the Dev Hatchery project board? (If so and it is supposed to be on the board it is currently on, which is the business board, the label should be "business" not dev hatchery as the dev hatchery label should only be used to identify items on the Dev Hatchery project board)

Or is this task supposed to say something like "Add a page to the dev hatchery wiki which contains design links" ? If that is what it is supposed to be then this task is labelled properly but should be on the dev hatchery project board and not the business board. Chris is the dev hatchery team lead and he won't be looking at the business board.

Thanks! :)

**Comment by northtwilight** [comment]
<Or is this task supposed to say something like "Add a page to the dev hatchery wiki which contains design links" ? > yes.
<then this task is labelled properly but should be on the dev hatchery project board and not the business board. > I know, couldn't find it when I wrote it at the time (though now of course that's not an issue)
Anyway, it'll get sorted now.
