### ISSUE TITLE
Create an issue template and provide a link to the document.

### ISSUE THREAD

**Issue by GrfxGuru** [CodeDoesGood/business#200]
Create a template that can be used for new issue tickets. Provide a link to the document.

**Comment by abbeyjackson** [comment]
I'd suggest this is better suited to the development board, also should be tagged projects not volunteers. The business board is for business operations tasks only like writing up policies and procedures, dealing with lega issues, etc.

**Comment by abbeyjackson** [comment]
Closed as duplicate
