### ISSUE TITLE
Create a wiki on how to organize an iOS project

### ISSUE THREAD

**Issue by swiftcode** [CodeDoesGood/business#211]
Create a wiki on some ways to keep an iOS project organized.

**Comment by abbeyjackson** [comment]
@mpc Nice idea! I think this would be good to put in the DevHatchery wiki
since it will be informational/ideas vs specific guidelines that must be
followed.

**Comment by swiftcode** [comment]
On hold.  09/13.  There may be a need for this, however the developers we have an experienced at iOS development and the decision on how the project should be laid out rests with the project lead.
