### ISSUE TITLE
Write Web suggested libraries

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#42]
Add to https://github.com/CodeDoesGood/org/wiki/4.-Recommended-Libraries

**Comment by Doug-Luce** [comment]
@abbeyjackson  Can I work on this?

**Comment by abbeyjackson** [comment]
@Doug-Luce Do you still want to do this? @GrfxGuru is available to help or to do it if you do not want to

**Comment by GrfxGuru** [comment]
I'll take this, have posted in dev-tools and dev-web asking for suggestions and began researching.

**Comment by swiftcode** [comment]
Will see if this is still needed and assign to an appropriate web developer.

**Comment by swiftcode** [comment]
This was completed by the web group.
