### ISSUE TITLE
Track Expenses

### ISSUE THREAD

**Issue by 98chimp** [CodeDoesGood/business#60]

**Comment by 98chimp** [comment]
Founders have been invited to a G-Sheet that includes all a history of all contributions and expenses (one-time and recurring).

**Comment by northtwilight** [comment]
It would be really cool if we could use a blockchain of some sort for verification purposes.

**Comment by 98chimp** [comment]
verification of what? not sure i follow

**Comment by abbeyjackson** [comment]
fyi I just edited your original comment Shahin to reflect the changed structure (instead of a shared file the file is now in the Accounting + Finance folder

**Comment by REWMassimo** [comment]
I don't know, I was thinking of situations when we might have to prove expenses as occurring or recurring.

**Comment by abbeyjackson** [comment]
@98chimp I'm going to close this issue because I feel this is an ongoing task that does not need to be open. Last night you set yourself a reminder to do it once a month. Let me know if you need anything from me to help facilitate this.
