### ISSUE TITLE
Hold Volunteer SW name contest

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#75]
Hold a contest with our volunteers to name our volunteer software

**Comment by GrfxGuru** [comment]
In progress with reminders to take part in the slack channels.

**Comment by abbeyjackson** [comment]
@GrfxGuru where are we at with this? Since I see people are not really participating you can always jump into the project room and decide with the team in there :)

**Comment by GrfxGuru** [comment]
I will follow up on this.

**Comment by GrfxGuru** [comment]
Poll this weekend to conclude and find a name. I will post a list to slack to select short list later today.

**Comment by abbeyjackson** [comment]
@GrfxGuru I think the clear winner was Mercury, right?

**Comment by GrfxGuru** [comment]
Yup Mercury it is.
