### ISSUE TITLE
Write Estimate Wiki Page

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#77]
Should include how to estimate projects given our volunteer time and also information about milestones

**Comment by abbeyjackson** [comment]
leads come up 3 - 4 milestones and provide an estimate for this
should be very compassion, we know your estimate will be wrong, everyone is volunteering, etc. Remember we are a teaching ground, the purpose is not to be accurate, but rather to teach hathclings how to do estimates.

**Comment by swiftcode** [comment]
The first draft is done.  Will have someone read it over and see if any changes are needed.

**Comment by swiftcode** [comment]
Made some revisions.  Closing ticket.
